import classes from "./MainContainer.module.scss";
import Head from "next/head";
import Navbar from "../../stateful/Navbar/Navbar";
const MainContainer = (props) => {
  return (
    <div className={classes.main_contianer}>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.navbar && <Navbar />}
      <div className={classes.container}>{props.children}</div>
    </div>
  );
};

export default MainContainer;
