import classes from "./MainContainer.module.scss";
import Head from "next/head";
import Navbar from "../../stateful/Navbar/Navbar";
const MainContainer = (props) => {
  return (
    <div style={{ maxHeight: props.fullHeight ? "100vh" : "100%" }}>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.navbar && <Navbar />}
      <div
        style={{ height: props.fullHeight ? "100%" : "auto" }}
        className={classes["Container"]}
      >
        {props.children}
      </div>
    </div>
  );
};

export default MainContainer;
