import Head from "next/head";
import styles from "../styles/Home.module.css";
// const Member = require("../Express-api/Models/member");
import classes from "./index.module.scss";
import MainContainer from "../Components/stateless/MainContainer/MainContainer";
import Notes from "../Components/stateless/Notes/Notes";
// import { login_validation } from "../next-utils/login_validation";
import Tasks from "../Components/stateful/Tasks/Tasks";
import Reports from "../Components/stateful/Reports/Reports";
import { protected_route_next } from "../next-utils/login_validation";
import {
  get_note_request,
  get_profile_request,
} from "../services/index_requests";

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer navbar>
        <main className={classes.Main_Container}>
          <div className={classes.Main_Container__Left}>
            <Notes />
          </div>
          <div className={classes.Main_Container__Right}>
            <Tasks setSendModelToggle userId={props.data.id} />
            <Reports />
          </div>
        </main>
      </MainContainer>

      <footer className={styles.footer}>this is a footer in index.js</footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  // const isLoggedIn = login_validation(context.req);
  const token = context.req && context.req?.cookies?.jwt;
  try {
    const id = await protected_route_next(context);

    const user_data = await get_profile_request(token);
    const notes = await get_note_request(token);
    // console.log("this is data of index:56", user_data, id);
    console.log("notes", notes, user_data);
    return {
      props: {
        data: user_data,
      },
    };
  } catch (error) {
    return {
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
    };
  }

  // if (!isLoggedIn.isLogged) {
  //   return isLoggedIn.redirect;
  // }

  // try {
  //   const id = isLoggedIn.isLogged;

  //   const profileData = await Member.findById(id).populate({
  //     path: "otherDetails",
  //   });
  // .select(
  //   "otherDetails firstName lastName fullName profilePicture profession"
  // );
  // if (!profileData)
  //   return {
  //     redirect: {
  //       permanent: false,
  //       destination: "/404",
  //     },
  //   };

  //   return {
  //     props: {
  //       data: JSON.parse(JSON.stringify(profileData)),
  //     },
  //   };
  // } catch (error) {
  //   return {
  //     redirect: {
  //       permanent: false,
  //       destination: "/404",
  //     },
  //   };
  // }
}

// SAVE IT FOR THE LATER
// export async function getServerSideProps({ req }) {
//   const protocol = req.headers['x-forwarded-proto'] || 'http';
//   const host = req.headers['x-forwarded-host'] || req.headers.host;
//   const baseUrl = `${protocol}://${host}`;

//   const res = await fetch(`${baseUrl}/api/data`);
//   const data = await res.json();

//   return {
//     props: {
//       data,
//     },
//   };
// }
